cd ..\src
javac test\*.java
javac fileManager\*.java
javac localSubprotocols\*.java
javac message\*.java
javac multicastThread\*.java
javac peer\*.java
javac remoteSubprotocols\*.java
Javac supportThreads\*.java
javac util\*.java
cd ..\scripts
